<header class="align-center">
    <h2>Save The BoyChild My Foot</h2>
    <p><em>Story By: Sibuor Madhako</em></p>
</header>
<p><b>If only women would stand up and speak frankly about how much they have invested in men, you would not have the audacity to open that thing you call a mouth and troll them. Your mates have gotten sisters bloated on champagne and all you are crying a river for is cheap liquor that made her almost throw up her intestines? Please!</b></p>
<p>Hello there? Remember me? Yes honey, it’s about that time. That time to have honest conversations. Very bold we will converse but in a very raw way. Saying it as it really is. Our friend with a face that is not so look able, let’s just say a human face has been putting his free time into good use. Behind the keyboard, he is stirring a spark online. He is a man on a mission, treading on murky waters, giving the boy child a voice and talking about the hush hush issues.</p>
<p>Don’t get me wrong, I have nothing personal against the brother. However, just the way there are two sides of a coin, so does a story. See, Africa’s most celebrated female writer Chimamanda Ngozi Adichie says there are imminent dangers on people’s perception after hearing just one side of the story. Today, I will honor the time you are spending reading this article by telling you the other side of the story.</p>
<p>Media personality Ciru Muriuki posted an interesting quote on her Facebook page. The good lady said if only women who had financed men in their lives would stand up, then the ‘save the boy child rant’ would become null and void. Ciru said nothing but the truth. So many women have spent debilitating painfully lump sum amount of money on brothers who they are no longer dating. Chances they got back their money? Haha honey you know the answer to that already, don’t you?</p>
<p>I am a proud member of this battalion of sisters who funded bros in their lives. I am a hustler by nature. My whole life revolves around hustle. ‘Don’t mess with my money’, is my slogan in life. However, money does not complete one. I have had my fair share of relation-shits. First on the list is a brother…let’s call him ‘N’. He was once broke and I sent him all the money I had on my phone. (It wasn’t much maybe 190 shillings, but I gave it out. honey in uni, that’s a fortune). </p>
<p>My second escapade was with a brother who had so much potential but his pocket did not reflect that. He would borrow petty cash from me and I would gladly give. I loved him and I wanted him to be comfortable so wholeheartedly I gave. Before we broke up, he borrowed five hundred shillings from me. (Let me repeat again, in college, this is a lot). The brother went ahead, got another babe and to date I can testify with a bible in my hand I am yet to see my money.</p>
<p>Last but not least the last one was the one that sucked me dry. Keep in mind am still in school, the brother would come to my house over the weekends. This meant breakfast, lunch and dinner on me. I would spend over 3000 shillings of my hard earned money feeding the brother. I showered him with gifts, gave out ‘cookie’ for free and even lent him some of my money. As usual, happily ever after is a façade. We are not together anymore. I forced myself to forget how his face looked like. Honey, imagine if it was you? Thank God guns are not sold in shops and neither are they sold to broke sponsorees!</p>
<p>What I lost is nothing. There are women who have lost hundreds of thousands from lending it out to men they love. Some gave voluntarily to help the bro start a business and stabilize. So what if men buy phones, we equally buy watches. What if they are forced to buy expensive hair, we also buy you people good shoes. So what if the man is cornered into taking a sister out. I have seen so many girls slide money under the table to the bro in order for him to pay. </p>
<p>Many women will not come forth and speak about it. Why? Isn’t it because of our culture? We live in the name and shame culture. We have shackled our girls with shame. If the man provides we glorify him, if it’s the woman providing, we direct her to shut up. For what, for the sake of the brothers ego, self-esteem, image and name among his friends. If all ladies could gather around and do the math of how much they have spent on bros, it would be enough to pay off Kenya’s national debt and fund every other girl’s liposuction and small change would be left to buy good hair.</p>
<p>Take a back seat brother, we are grateful that you provide. Correct me if am wrong but that is the sole responsibility of a man, providence right? It’s also never by force. If you have 3000 shillings like myself, a blue suit, brown shoes and a loud mouth full of plans, don’t wave through your wallet. Later, you are forced to do a press conference of how women are gold diggers. Which gold? Honey what you have does not even amount to gold dust. Sit your stiff butt down!</p>
<p><b>PS: </b><em>Some other man has gotten a sister bloated on champagne and all you are crying a river for is cheap liquor that made her throw up her intestines? Please! Oh and the part I said our brothers crusader has a human face, mine is human too. Takes one to know one. Haha!</em></p>