          <header class="align-center">
            <h2>OUR DONATION TO HEAVEN</h2>
            <p><em>Story By: Trix</em></p>
          </header>
          
          <p>Death is an inevitable cycle of life and for every minute one is born another is lost. The sports sector has kept us entertained for most of the weekends with the different local leagues but 2017 on its part seems to have been selfish with this industry. A dark cloud has loomed over for the whole year with the loss of young and talented players. From January to November, grief has been conjoined as part of their lifestyle. A minute of silence has been a norm before most of the matches with the Kenya Rugby Union having to bear most of the grief each month determined to prove how many gems it could bag down. </p>
          <div>
            <img src="<?php echo base_url('images/'); ?>dec-openforum.jpg" alt="sports men">
          </div>
          <p>January 15th kicked in with the loss of Andrew Wekesa a Homeboyz rugby prop who was murdered in Mlololgo, Machakos County under unclear circumstances just a few weeks after the passing on of Gachui and Wayodi in December 2016. While Andrew’s grave soil was still fresh another blow hit the KRU with the death of Western Bulls center Emmanuel Musasia on February 13th after a short illness. March and April were kind enough to spare us the loss of other great talents and prepare our tear glands for more overwhelming times coming next. </p>
          <p>Athletics Kenya was not spared either as June 1st saw the untimely death of David Kiprotich who collapsed while training at Kiptagat, Uasin Gishu County and was pronounced dead on arrival at The Moi Teaching and Referral Hospital. Just like that. July 24th saw us lose James Kilonzo a KCB rugby center who was shot dead by unknown people while withdrawing money at Kasarani, Sunton area. Black August was ready for us with the death of USIU rugby center Mike Ouma who had an Accident in his apartment in South B just a few days after Kilonzo was laid to rest. September 24th saw the Hokey Union Join in the mourning band wagon after the demise of Paul Juma from Butali sugar who succumbed to injuries sustained after a fatal road accident.</p>
          <p>The last quarter has shown its darker shade with a majority of the deaths occurring in close sequence. USIU Spartan Martha Masinde aka Sasha collapsed in their home in Bungoma never to wake up again on 28th October. For a moment, her untimely death diverted our attention from the then ongoing AFCON games in Egypt to celebrate the life of this ever-smiling soul. November 4th saw the demise of Mike Okombe, a Nakuru RFC flanker who was stabbed to death by his longtime girlfriend after a fight and before the elapse of 24hrs KRU was in mourning again former homeboyz rugby skipper Peter Wekesa with his twin brother John Wekesa who were elder brothers to Andrew Wekesa passed on after a road accident in Mariakani. It must have been a tough and sad time for their family losing three sons in a year. 7th November saw KHU back in a somber mood, ex Kenyan International Rodgers Ayuya met his death in a road accident in Bungoma and was the only one who died of the other 15 passengers. Before his death, Ayuya last played for the Western jaguars in the 2016/2017 season. Thomas Aseka, a Mumias RFC prop was not spared either when death came knocking, on November 9th he was found dead in his apartment in Mumias resulting from Pulmonary Embolism. </p>
          <p>KRU held a rugby prayer day on 12th November a day after the impala floodlit quarters and two days later the curse of November was taunting them with the death of George Gachui aka Pozza quins’ forward and veteran who died under ‘mysterious circumstances’. According to blogger Cyprian Nyakundi, it was a successful suicide attempt.</p>
          <p>I don’t really understand the mystery bit in all these deaths. Is it the fact that they total up to twelve a clear representation of the total months in a year each month of 2017 having received its fair share of a donation? Or are they all untimely deaths where the players’ life had been cut shot by one simple action that could have been avoided. The Wekesa’s, Ayuya and Juma could have avoided using the roads on their different death time. Kilonzo should not have gone to withdraw his money at that given time.  Mike on the other hand, should not have gone to his apartment on that day. As for Okombe, he should have stayed home and avoided that party and just maybe their lives could have been spared. Are we looking at a spiritual warfare here? Or is it just fate and nature taking its course? I have no answers to all this but for sure heaven gained the best from all these teams. </p>
          <p>Sports is a mixture of guts, blood and sweat. These champs showed their powers in the different pitches they played on, but each of them could not fight this one last battle. December please spare us any more tears! May our donations ensure long life for a more celebratory 2018 sports season.</p>


