<header class="align-center">
    <h2>REIGNITING THE SEXUAL SPARK</h2>
    <p><em>Story By: Akinyi D. Osongo</em></p>
</header>
<center><img src="<?php echo base_url('images/')?>sex101feb18.jpg"></center>
<p>Don’t be surprised, the porn I am talking about is definitely pornography and yea, contrary to many believes that pornography ruins relationships by setting unrealistic expectations in the bedroom it can also be used to improve sex life. I once had this conversation with my peers and the nays were more that the yes but when I asked them if they watch porn, a large number said yes. So the question is why watch porn when you can’t use it to spice up your sex life?  </p>
<p>A study published in the Journal Sexual Medicine shows that watching porn at least 40 minutes in a fortnight can boost your sex drive and an overall desire to have sex. Most of the people I spoke to were not worried about watching porn but they were convinced that porn would take their attention away from their partner but it should be known that watching porn does not mean you have to masturbate - that is what will take away your sex drive and not the porn itself. Masturbation is something we will take a look at deeply on another day. So how can one incorporate porn into their sex life in a way that it works to their advantage?</p>

<div class="row">
    <div class="col-sm-4">
        <center><img src="<?php echo base_url('images/');?>sex101feb183.jpg"></center>
    </div>
    <div class="col-sm-8">
        <p>Who needs foreplay after watching porn? This is especially vital to that married couple who have kids knocking at their door after every five minutes. Life will be moving fast and even that ‘quickie’ has to be hot and fast than before. Research shows that men and women alike begin displaying arousal within 30 seconds of watching porn. </p>
        <p>This is also great for the just married couples who are virgins and new to the sex issue. However, this is something you should both agree on and do together. You shouldn’t spring on a new style to your partner that you saw in pornography before agreeing on it. If you both like what you see and what you do when you try it, then that deal is a success. This should not be a hard subject to start. “I want to show you something that turns me on.”That should do it. Just be careful not to imply that watching porn is your proposed solution to a lackluster sex life.</p>
    </div>
</div>
<p>Watching porn is also an easy way to learn about your partner’s fantasy. Fantasy is part of a healthy sex life and porn adds to the repository of sex scenarios in our heads. Most of the times you don’t even know you like something until you see it; furthermore most of us are shy or ashamed about sharing our sexual fantasies with our partners. Thanks to porn you can learn very fast what makes your partners engine rev. In porn you can find precious information that can be used to please your partner. After all a good partner aims to please. The internet has a variety of video clips with professionals and amateurs playing out any and every possible sexual act. Watch the clip together and in the end you will both learn what turns you on and what you will never do even with a gun pointed at your head.</p>
<p>Porn may lessen the need to act out on sexual desires outside of your relationship. It is considered one of the ways to avoid cheating. This is especially so to a man who thinks the mother of his children cannot perform some acts when those acts actually turn her on. Porn will help you let home be the place where all of your sexual needs and fantasies are met. If you can get dirty with your partner you’re less likely to look for gratification elsewhere. It is also human nature to crave variety and allowing your partner to view porn will not wreck your relationship, actually forbidding them is what will put a strain in it. This will involve a lot of lies where he/she has to clear the laptops ‘history’ and do other stuff behind your back. Do it together in openness and honesty rather than act like what you both need is shameful secret that should be kept hidden. Porn will also help you foster emotional and sexual intimacy. A significant portion that sex therapists use to help couples develop a deeper sexual connection is erotic images.</p>
<p>However, the fact that porn can inspire your sex life doesn’t make it an accurate reflection of sex. So don’t expect your partner to look like a porn star or have to use sexual positions that require one to train in aphrodisiac for Olympics. Take what you’re watching with a grain of salt and when it gets ridiculous you can even share a good laugh over it. As much as most people do not want to admit it, sex is also glue that keeps a relationship together. If you and your mate haven’t included pornography in your sexual basket then there is no time like now to discuss this. After all couples that play together stay together. </p>