<header class="align-center">
    <h2>Healing Myself Through Meditation</h2>
    <p><em>Story by : Ondiro Oganga</em></p>
</header>

<p><strong>“The purpose of meditation is to develop higher faculties. Without this development, understanding deeper spiritual truths is not possible.” Grand Master Choa Kok Sui</strong></p>
<p>A lady who I know, love and did her story sometime back, posted on her Instagram that she was willing to take someone through twin heart meditation. I have never meditated before. However, mine has not been an easy ride and I jumped on the opportunity.</p>
<p>As preparation for the meditation, I had to go in with a pure body, mind and soul. For body, I was not to take beef that night and in the morning, I was to have a salt bath to rid me off negative energy. For mind and soul, how about we jump right into it in the next paragraph?</p>
<p>At exactly 8:15 I was at her door. Right before the meditation started, the good lady shared me with a cup of tea. She also shared with me something else, Tissue. Before we begun, I had a lot of baggage that I has bottled in me. So, first off, I had to shed all that off. In readiness for the meditation, I had to be free of everything, anger, malice and my unforgiving nature. </p>
<p>As we begun the meditation, we did a set of twelve exercises. They ranged from eye, neck, shoulders, hands, waist, legs and even ankles. We then did a set of fifty squats as we said out loud beautiful affirmations to ourselves such as, I am beautiful, I am worthy, I am amazing and I am enough.</p>
<p>The meditation in itself was powerful. It makes you shut out every other thing and focus on you. You become present, aware of the moment. All the senses in my body were heightened. My body was no longer a just that, body! It became an integral part. I felt energy flow in me. From head to my toe. Sitting in a meditating position, energy was flowing through my body, I could feel it in the pal of my hands.</p>
<p>One of the basic laws of life says whatever you give you get. The meditation teaches you to give love and light to the world. We blessed the earth. We imagined the earth was in front of us. We thought positive thoughts over it. Imagine, the world has over seven billion people. One person, sending love and light to all seven billion people. Think of it, how much love and light will you receive as an individual?</p>
<p>While in the moment of meditation, one thing became crystal clear to me. I have to forgive and forget. The anger was eating me up deep inside. The rotten seed of hate had taken root in my system. The fruits were too heavy for my conscience to bear. The worst part is that the struggle showed. People took notice and this is the one lady I laid bare my struggle and the meditation was my first step to recovery. </p>
<p>Time flew and we were almost done. One thing was clear. Earlier, my friend had said I should not go into the meditation with expectations. Rather, I should focus on the light. Ladies and gentlemen, that was true. When you rid yourself off expectations, which tend to be bias to the rule of nature, you become conscious of who you truly are and what you truly need. </p>
<p>My expectations would be for this magazine to begin making me millions. What I truly needed was to find myself. The noise was drowning my hum. A hum that was the core of my being. My body had fallen out of synchrony. My body was saying this, my mind that and my soul was wallowing in a deep dark sea. The light pointed out the most important thing, I needed healing. I needed to heal my body, my mind and my soul.</p>
<p>The journey has just begun. Every morning, I read out to myself beautiful affirmations. I am far away from healing, self-awareness and truly finding my purpose in life. I am getting there. One issue is being treated, but there are a million and one other underlying that will be revealed to me as I go. One thing that I know for sure though, I have never felt as much peace and wholeness as I felt after my twin heart meditation. </p>
<p>This article barely does justice to Twin Heart Meditation. You should try it out. Your experience might not be similar to mine. However, it will be the beginning of your awakening. Do not hold back. Take back charge of your life. Pursue wholeness. You will not regret the experience!</p>
<p>“Just as Pranic Healing can ‘miraculously’ cure simple and severe ailments, the Meditation on Twin Hearts, when practiced by a large number of people, can miraculously heal the entire earth; thereby making the earth more harmonious and peaceful.” Master Choa Kok Sui</p>